version: '3.8'

services:
  api:
    build:
      context: ./eksamens_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./eksamens_backend:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./eksamens_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./eksamens_frontend:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: api
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: